# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empathy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('trainer', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
